version: '2'
services:
  app:
    image: app
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=jm_shcoll_test
